export {
  ResponsiveImage,
  BLOG_IMAGE_SIZES,
  BLOG_IMAGE_WIDTHS,
  GALLERY_IMAGE_SIZES,
  GALLERY_IMAGE_WIDTHS,
  HERO_IMAGE_SIZES,
  HERO_IMAGE_WIDTHS,
  SERVICE_IMAGE_SIZES,
  SERVICE_IMAGE_WIDTHS,
} from "./ResponsiveImage";
